### ISSUE TITLE
flask와 mysql 연동 및 file 구조화

### ISSUE THREAD

**Issue by zmrdltl** [Kidulting/hw-compiler-server#3]

**Comment by zmrdltl** [comment]
@Psolmin mysql과 flask를 연동시 pymysql이 더 나아보이네요. ORM 형태 sqlalchemy는 현재 원격 db server를 구축한 상태에서는 불필요해 보입니다. 어떻게 생각하시나요?

**Comment by zmrdltl** [comment]
@Psolmin 
pymysql은 외부 module이라 flask 친숙한 flaskext module 설치해서 시행해보니 db 연결 및 query실행이 원활한 점을 확인했습니다. 이 쪽으로 pr 보내보겠습니다.

**Comment by Psolmin** [comment]
@zmrdltl 
아 좋습니다 우선 회의한대로 pymysql를 설치하여 진행한 내용입니다.
그때 이해하기로 pymysql을 사용하도록 config로 설정해서 sqlalchemy로 연결하는거라고 생각했는데 어떤 방식으로 동작하는 지 자세히 찾아봐야겠습니다 :)

**Comment by zmrdltl** [comment]
이쪽 부분은 flaskext.mysql package 사용하는 것으로 결론 지어졌습니다.
